### ISSUE TITLE
[bug] Command completion

### ISSUE THREAD

**Issue by NStefan002** [JesperLundberg/svartafanan.nvim#3]
Command completion gives invalid results.

https://github.com/JesperLundberg/svartafanan.nvim/assets/100767853/f3f1b6f2-6851-4031-b27f-5b8ab28db3e5

**Comment by JesperLundberg** [comment]
That is actually quite odd.

I tried it (before updating to what I merged here above) and for me it worked when I did the exact same thing that you did.

I think your solution is better as mine popped up the menu with the choices rather than autocomplete the "proper" way.
